### ISSUE TITLE
[Improvments] Prettify dose not work on code sections

### ISSUE THREAD

**Issue by AhmedBHameed** [koliberr136a1/docsify-rtl#1]
You may add another property to keep \<pre\> tag direction. Changing pre tag direction causes prettify to set all codes in line indents.

I solve it by using custom style on top of the file:

```html
<style>
      pre {
        direction: ltr;
      }
</style>
```

**Comment by ckoliber** [comment]
Thanks @AhmedBHameed

bug fixed
